version: "3.8"

services:
  smartzap:
    container_name: smartzap
    image: ghcr.io/optivradigital/smartzap:latest
    restart: always
    ports:
      - "127.0.0.1:3002:3002"
    env_file:
      - .env
    networks:
      - smartzap_default
      - evolution-net

networks:
  smartzap_default:
    driver: bridge
  evolution-net:
    external: true
